---
- hosts: unifictl
  become: true
  become_user: root
  tasks:
    - name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
      raw: systemctl disable --now {{item}}
      with_items:
        - 'apt-daily.timer'
        - 'apt-daily-upgrade.timer'

    - name: Reload systemctl daemon to apply the new changes
      raw: systemctl daemon-reload

    - name: Wait for any possibly running unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Purge unattended upgrades
      raw: apt-get -y purge unattended-upgrades  

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
              update_cache: yes
              force_apt_get: yes
              cache_valid_time: 3600

    - name: Slim down pkgs for update
      apt:
              autoremove: yes
              purge: yes


    - name: Upgrade all packages on servers
      apt:
              upgrade: dist
              force_apt_get: yes

    - name: Cleanup
      apt:
              autoremove: yes
              purge: yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
