apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: bastion
spec:
  selector:
    matchLabels:
      app: bastion
  replicas: 2
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: bastion
        image: "cloudposse/bastion:latest"
        env:
        - name: "PORT"
          value: "22"
        - name: "MFA_PROVIDER"
          value: "google-authenticator"
        volumeMounts:
        - name: bastionkey
          mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
          readOnly: true
      volumes:
      - name: bastionkey
        configMap:
          name: bastionkey
